<a href="https://colab.research.google.com/github/dilipkumari20/test/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip3 install numpy

In [ ]:
import numpy as np
marks = np.array([82,99,87,54,98,43])
marks_list = [82,99,87,54,98,43]
print(marks)
print(type(marks))
print(marks_list)
print(type(marks_list))

[82 99 87 54 98 43]
<class 'numpy.ndarray'>
[82, 99, 87, 54, 98, 43]
<class 'list'>


In [ ]:
marks = np.array([82,99,87,54,98,43])
print(marks+5)

[ 87 104  92  59 103  48]


In [ ]:
marks = np.array([82,99,87,54,98,43])
print(marks-10)


[72 89 77 44 88 33]


In [ ]:
marks = np.array([82,99,87,54,98,43])
print(marks/5)

[16.4 19.8 17.4 10.8 19.6  8.6]


In [ ]:
marks = np.array([82,99,87,54,98,43])
print(marks//5)

[16 19 17 10 19  8]


In [ ]:
prices = np.array([100, 250, 50, 300 ])
quantities = np.array([2, 1,5, 3])
print(prices * quantities)

[200 250 250 900]


In [ ]:
prices = np.array([100, 250, 50, 300 , 400])
quantities = np.array([2, 1,5, 3])
print(prices * quantities)

ValueError: operands could not be broadcast together with shapes (5,) (4,) 

In [ ]:
prices = np.array([100, 250, 50.2, 300 , 400])
print(prices)

[100.  250.   50.2 300.  400. ]


In [ ]:
mylist =[1,"hello", True]

print(np.array ([1,"hello", True]))

['1' 'hello' 'True']


In [ ]:
print(np.array([2, True]))

[2 1]


HAndy ways to create Numpy array

In [ ]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [ ]:
zeros = np.ones(51)
print(zeros)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1.]


In [ ]:
fives = np.full(5,9)
print(fives)

[9 9 9 9 9]


In [ ]:
fives = np.full(5,1)
print(fives)

[1 1 1 1 1]


In [ ]:
numbers = np.arange(0,10,2)
print(numbers)

[0 2 4 6 8]


In [ ]:
print(np.linspace(5,9))

[5.         5.08163265 5.16326531 5.24489796 5.32653061 5.40816327
 5.48979592 5.57142857 5.65306122 5.73469388 5.81632653 5.89795918
 5.97959184 6.06122449 6.14285714 6.2244898  6.30612245 6.3877551
 6.46938776 6.55102041 6.63265306 6.71428571 6.79591837 6.87755102
 6.95918367 7.04081633 7.12244898 7.20408163 7.28571429 7.36734694
 7.44897959 7.53061224 7.6122449  7.69387755 7.7755102  7.85714286
 7.93877551 8.02040816 8.10204082 8.18367347 8.26530612 8.34693878
 8.42857143 8.51020408 8.59183673 8.67346939 8.75510204 8.83673469
 8.91836735 9.        ]


In [ ]:
print(np.linspace(5,9,4))

[5.         6.33333333 7.66666667 9.        ]


In [ ]:
marks = np.array([85, 92, 78, 95, 88])

print(marks.shape)
print(marks.ndim)
print(marks.size)
print(marks.dtype)
print(len(marks))

#If one of the values were 'error', conversion to int would fail.
# NumPy would assign a string dtype to hold mixed data.
# In that case, numerical operations (sum, max, min) would not behave correctly.

(5,)
1
5
int64
5


In [ ]:
a_list = [1, 2, 3]
b_list = [4, 5, 6]

a_array = np.array([1, 2, 3])
b_array = np.array([4, 5, 6])

print(a_list + b_list)
print(a_array +b_array)



[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)  #addition
print(a-b)   #subtraction
print(a*b)   #multiplication
print(a/b)
print(a//b)
print(a%b)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]
[  1  32 729]


In [ ]:
marks = np.array ([85, 92, 78, 95, 78, 99, 36, 27, 56, 77])
print(marks.sum())
print(marks.min())
print(marks.max())
print(marks.mean())

723
27
99
72.3


In [ ]:
import numpy as np

# 1D array
a = np.array([10, 20, 30, 40, 50])
print(a.shape)    # (5,)     — 5 elements, 1 dimension
print(a.ndim)     # 1        — 1 dimen

(5,)
1


In [ ]:
# 2D array (matrix)
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)    # (2, 3)   — 2 rows, 3 columns
print(b.ndim)

(2, 3)
2


In [ ]:
# 3D array
c = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
print(c)
print(c.shape)    # (2, 2, 2) — 2 blocks, 2 rows, 2 columns
print(c.ndim)     # 3         — 3 dimensions

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [ ]:
import numpy as np

arr_ = np.array([[[[[[1, 2], [3, 4]],
                     [[5, 6], [7, 8]]],

                        [[[9, 10], [11, 12]],
                        [[13, 14], [15, 16]]]]]])

print(arr_.shape)

(1, 1, 2, 2, 2, 2)


In [ ]:
array = np.array([10, 20, 30.0])
print(array.dtype)

float64


Array shapes

In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
print(a)
print(a.shape)
print(a.T)
print(a.T.shape)

[10 20 30 40 50]
(5,)
[10 20 30 40 50]
(5,)


In [ ]:
print(a.T)
print(a.T.shape)

[10 20 30 40 50]
(5,)


In [ ]:
a = np.array([[10], [20], [30], [40], [50]])
print(a)
print(a.shape)
print(a.T)
print(a.T.shape)

[[10]
 [20]
 [30]
 [40]
 [50]]
(5, 1)
[[10 20 30 40 50]]
(1, 5)


In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b)
print(b.shape)
print(b.T)
print(b.T.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
c = np.array([[[1,2],[3,4],
               [6,7],[8,9]]])
print(c.shape)
print(c)

(1, 4, 2)
[[[1 2]
  [3 4]
  [6 7]
  [8 9]]]


In [ ]:
c = np.array([[[1,2],[3,4]],
               [[6,7],[8,9]]])
print(c.shape)
print(c)
print(c.T)
print(c.T.shape)

(2, 2, 2)
[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]
[[[1 6]
  [3 8]]

 [[2 7]
  [4 9]]]
(2, 2, 2)


In [ ]:
c = np.array([[[1,2],[3,4],
               [6,7],[8,9]]])
print(c.shape)
print(c)

(1, 4, 2)
[[[1 2]
  [3 4]
  [6 7]
  [8 9]]]


In [ ]:

numbers = np.arange(1,13)
print(f"original: {numbers}")
print(f"shape: {numbers.shape}")

original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)


In [ ]:
table = numbers.reshape(3,4)
print(f"\nreshaped to (3,4)")
print(table)


reshaped to (3,4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
numbers = np.arange(1,12)
print(f"original: {numbers}")
print(f"shape: {numbers.shape}")


original: [ 1  2  3  4  5  6  7  8  9 10 11]
shape: (11,)


In [ ]:
numbers = np.arange(1,13)
print(f"original: {numbers}")
print(f"shape: {numbers.shape}")
table = numbers.reshape(2,6)
print(f"\nreshaped to (3,4)")
print(table)

original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape: (12,)

reshaped to (3,4)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [ ]:
table = numbers.reshape(2,2,3)
print(f"\nreshaped to (3,4)")
print(table)


reshaped to (3,4)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
numbers = np.arange(1,13)
print(numbers.reshape(3,-1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(numbers.reshape(-1,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
b = np.array([[1,2,3],
              [4,5,6]])
print(b.reshape(-1))

[1 2 3 4 5 6]


In [ ]:
print(table.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


speed test

In [ ]:
import numpy  as np
import time
size = 100000000

python_list = list(range(size))
start =time.time()
for i , v in enumerate(python_list):
    python_list[i] = v+i
list_time =time.time() - start

numpy_array = np.arange(size)
start =time.time()
result_array =numpy_array + 1
numpy_time =time.time() - start

print(f"Python list: {list_time:.4f} seconds")
print(f"NumPy array: {numpy_time:.4f} seconds")
print(f"NumPy is {list_time / numpy_time:.0f}x faster! 🚀")

Python list: 18.6581 seconds
NumPy array: 0.2655 seconds
NumPy is 70x faster! 🚀


In [ ]:
import numpy  as np
import time
size = 100

python_list = list(range(size))
start =time.time()
for i , v in enumerate(python_list):
    python_list[i] = v+i
list_time =time.time() - start

numpy_array = np.arange(size)
start =time.time()
result_array =numpy_array + 1
numpy_time =time.time() - start

print(f"Python list: {list_time:.4f} seconds")
print(f"NumPy array: {numpy_time:.4f} seconds")
print(f"NumPy is {list_time / numpy_time:.0f}x faster! 🚀")

Python list: 0.0002 seconds
NumPy array: 0.0025 seconds
NumPy is 0x faster! 🚀


Array slicing

In [ ]:
import numpy as np

# From nested lists
marks = np.array([
    [85, 92, 78],    # Rahul's marks in 3 subjects
    [90, 88, 95],    # Priya's marks
    [72, 65, 80],    # Amit's marks
    [95, 91, 89]     # Sneha's marks
])

print(marks)
print(f"Shape: {marks.shape}")    # (4, 3) — 4 students, 3 subjects
print(f"Dimensions: {marks.ndim}")  # 2
print(f"Total elements: {marks.size}")  # 12

[[85 92 78]
 [90 88 95]
 [72 65 80]
 [95 91 89]]
Shape: (4, 3)
Dimensions: 2
Total elements: 12


In [ ]:
marks[0,0]

np.int64(85)

In [ ]:
marks[2,1]

np.int64(65)

In [ ]:
marks[0]

array([85, 92, 78])

In [ ]:
marks[:,0]

array([85, 90, 72, 95])

In [ ]:
marks[:,2]

array([78, 95, 80, 89])

In [ ]:
marks[0:2,:]

array([[85, 92, 78],
       [90, 88, 95]])

In [ ]:
marks[:,0:2]

array([[85, 92],
       [90, 88],
       [72, 65],
       [95, 91]])

In [ ]:
marks[1:3,1:3]

array([[88, 95],
       [65, 80]])

In [ ]:
marks[-1]

array([95, 91, 89])

In [ ]:
marks[-2]

array([72, 65, 80])

In [ ]:
marks[:,-1]

array([78, 95, 80, 89])

In [ ]:
marks[:,-2]

array([92, 88, 65, 91])

In [ ]:
marks[1:-1,0:-2]

array([[90],
       [72]])

In [ ]:
import numpy as np

A = np.array([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])

B = np.array([0, 1, 2])

print(A+B)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [ ]:
import numpy as np

A = np.array([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])

B = np.array([0, 1, 2])

print(A*B)

[[ 0  0  0]
 [ 0 10 20]
 [ 0 20 40]
 [ 0 30 60]]


In [ ]:
import numpy as np

A = np.array([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]
])

B = np.array([0, 1, 2,4])

print(A+B)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

random numbers generation in numpy

In [ ]:
import numpy as np
print(np.random.randint(1,25))

18


In [ ]:
import numpy as np
print(np.random.randint(1,100))

32


In [ ]:
import numpy as np
print(np.random.randint(1,125))

17


In [ ]:
import numpy as np
print(np.random.randint(1,25, size =10))

[21 23 14  3 21 24 16  1  3 21]


In [ ]:
import numpy as np
print(np.random.randint(1,25, size =(5,2)))

[[ 1  1]
 [15  9]
 [14  3]
 [ 7  4]
 [11  2]]


In [ ]:
np.random.random(5)

array([0.35987014, 0.77568026, 0.41472162, 0.69969459, 0.75054108])

In [ ]:
import numpy as np
np.random.uniform(20,45,size =7)

array([24.49103797, 30.69132025, 40.65545334, 29.54985702, 32.38663973,
       34.31436986, 34.04229643])

In [ ]:
np.random.choice(np.random.uniform(20,45,size =7),size=3)

array([41.5356199, 44.2204034, 28.3247046])

In [ ]:
array1 = np.random.uniform(20, 45, size= 7)
print(array1)

np.random.shuffle(array1)
print(array1)

[42.16757034 26.84534999 33.963386   26.83622575 33.19778845 24.6972998
 37.40474163]
[24.6972998  37.40474163 26.84534999 26.83622575 33.963386   42.16757034
 33.19778845]


In [ ]:
cities = np.array(["mumbai", "delhi", "bangalore", "chennai", "pune"])
picks = np.random.choice(cities, size =1)
print(picks)

['bangalore']


In [ ]:
cities = np.array(["mumbai", "delhi", "bangalore", "chennai", "pune"])
picks = np.random.choice(cities, size =3)
print(picks)

['delhi' 'pune' 'bangalore']


In [ ]:
cities = np.array(["mumbai", "delhi", "bangalore", "chennai", "pune"])
picks = np.random.choice(cities, size =3,replace = False)
print(picks)

['mumbai' 'chennai' 'bangalore']


Stimulate

In [ ]:
print(np.random.randint(1,7))

5


In [ ]:
picks = np.random.choice(np.array(["Heads", "Tails"]),size = 1)
print(picks)

['Tails']


Seed paramater

In [ ]:
print(np.random.randint(1,100, size=5))
print(np.random.randint(1,100, size=5))

[82 30 53 71 74]
[59 24 90 64 95]


In [ ]:
print(np.random.randint(1,100, size=5))
print(np.random.randint(1,100, size=5))

[58 19 65 25 69]
[60 23  9 96 26]


In [ ]:
np.random.seed(100)
print(np.random.randint(1,100, size=5))

[ 9 25 68 88 80]


In [ ]:
np.random.seed(42)
print(np.random.randint(1,100, size=5))

[52 93 15 72 61]


In [ ]:
np.random.seed(100)
print(np.random.randint(1,100, size=5))

[ 9 25 68 88 80]


In [ ]:
import numpy as np
np.random.seed(40)
num_students = 20
first_names = np.random.choice(["Rahul", "Vinay"," Bindu", "Somya", "Harsha","Sakith","Mounika"],
                               size= num_students)
print(first_names)
cities = np.random.choice(["vizag","Hyderabad","Kakinada","Chennai","Pune","Warangal","ongole"],
                          size = num_students)
print(cities)
ages = np.random.randint(18, 26, size = num_students)
print(ages)

chemistry = np.random.randint(40, 100, size = num_students)
print(chemistry)
english = np.random.randint(40, 100, size = num_students)
print(english)
physics = np.random.randint(40, 100, size = num_students)
print(physics)
maths = np.random.randint(40, 100, size = num_students)
print(maths)


['Mounika' 'Somya' 'Sakith' 'Rahul' 'Rahul' ' Bindu' 'Vinay' 'Harsha'
 ' Bindu' 'Somya' ' Bindu' 'Somya' 'Somya' 'Somya' 'Vinay' 'Rahul' 'Vinay'
 'Sakith' 'Vinay' 'Rahul']
['Pune' 'ongole' 'ongole' 'Pune' 'Pune' 'vizag' 'Kakinada' 'Kakinada'
 'ongole' 'Chennai' 'Chennai' 'Chennai' 'Hyderabad' 'Chennai' 'Warangal'
 'Pune' 'Warangal' 'Warangal' 'Kakinada' 'Kakinada']
[25 20 21 24 22 22 24 25 19 21 21 20 20 25 20 22 23 18 19 25]
[68 81 75 71 83 64 87 69 93 86 65 59 98 74 46 97 97 59 61 76]
[77 77 84 50 64 40 41 73 92 48 97 74 54 93 54 47 96 53 62 60]
[58 67 52 66 49 98 95 91 67 97 40 61 70 93 77 72 91 90 98 60]
[81 95 82 78 54 95 87 83 67 52 69 85 47 50 59 44 65 92 95 74]


In [ ]:
with open("students.txt", "w") as file:
    file.write("Name,City,Age,Maths,Physics,Chemistry,English \n" )


    for i in range(num_students):
        file.write(f"{first_names[i]}, {cities[i]}, {ages[i]},{maths[i]}, {physics[i]}, {chemistry[i]}, {english[i]} \n")

Task1:


In [ ]:
with open("warehouse_data.txt","w") as file:
     file.write("120 \n")
     file.write("85\n")
     file.write("200\n")
     file.write("95\n")
     file.write("150")

In [ ]:
with open("warehouse_data.txt","w") as file:
     file.write("120 \n")
with open("warehouse_data.txt","a") as file:
  # If 'w' mode is replaced with 'a' (append) mode
  # the new data will be added to the end of the file instead of overwriting it.
     file.write("85\n")
     file.write("200\n")
     file.write("95\n")
     file.write("150")


Task2:

In [ ]:
with open("warehouse_data.txt","r") as file:
     lines = file.readlines()
     print(lines)

     for each_line in lines:
        print(each_line)
# I used readlines() because it reads all lines at once
#stores them in a list
# read() it reads all data one time & stores data as string

['120 \n', '85\n', '200\n', '95\n', '150']
120 

85

200

95

150


In [127]:
import numpy as np
with open("warehouse_data.txt","r") as file:
     print(file.readlines())
     #values = file.readlines
     for line in lines:
         values = line.strip("\n")
         print(values)

#array = np.array(values)
values = [int(line.strip()) for line in lines]
print(values)

array = np.array(values)
print(array)
print(array.dtype)
print(array.shape)
print(array.size)
print(array.sum())
print(array.min())
print(array.max())


['120 \n', '85\n', '200\n', '95\n', '150']
120 
85
200
95
150
[120, 85, 200, 95, 150]
[120  85 200  95 150]
int64
(5,)
5
650
85
200
